name: Build and Push Dynamic Dockerfile

on:
  push:
    paths:
      - 'comfyui-with-flux/Dockerfile'  # 모든 디렉토리의 Dockerfile에 대한 변경 감지

jobs:
  build:
    runs-on: ubuntu-22.04

    steps:
      # 1. 저장소 체크아웃
      - name: Checkout repository
        uses: actions/checkout@v2

      # 2. Docker 메타데이터 생성
      - name: Docker meta
        id: docker_meta
        uses: crazy-max/ghaction-docker-meta@v1
        with:
          images: ${{ jodog0412/comfyuiwithflux }}
          tag-semver: |
            {{version}}
            {{major}}.{{minor}}

      # 3. Docker Buildx 설정
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      # 4. Docker Hub 로그인
      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      # 5. Docker 이미지 빌드 및 푸시
      - name: Build and push Docker image
        uses: docker/build-push-action@v2
        with:
          context: ${{ comfyui-with-flux/Dockerfile }}
          file: ${{ comfyui-with-flux/Dockerfile }}
          platforms: linux/amd64
          push: true
          tags: ${{ steps.docker_meta.outputs.tags }}
          labels: ${{ steps.docker_meta.outputs.labels }}
